### ISSUE TITLE
Cloud Build のデフォ

### ISSUE THREAD

**Issue by iganari** [iganari/package-gcp#103]
```
steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-f', 'Dockerfile', '--tag=gcr.io/project-id/aaaaa:1.2', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ["push", "gcr.io/project-id/test-web:1.2"]
cloudbuild.yaml
```
