### ISSUE TITLE
気軽に使えるContainerの脆弱性スキャンツール Trivy

### ISSUE THREAD

**Issue by iganari** [iganari/package-gcp#84]
https://tech.recruit-mp.co.jp/infrastructure/continuous-integration-vulnerability-detection-tool-trivy/

**Comment by iganari** [comment]
```
- name: 'aquasec/trivy'
  entrypoint: sh
  args:
    - -c
    - |
      trivy --exit-code=1 --severity=CRITICAL -o /dev/stdout  gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA
      if [ $? != 0 ];then echo "脆弱性を検知しました";exit 1;fi
```
